# Generated by Django 3.0.2 on 2020-01-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sort', models.TextField(blank=True, null=True)),
                ('link', models.TextField()),
            ],
            options={
                'db_table': 'authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('sort', models.TextField(blank=True, null=True)),
                ('timestamp', models.TextField(blank=True, null=True)),
                ('pubdate', models.TextField(blank=True, null=True)),
                ('series_index', models.FloatField()),
                ('author_sort', models.TextField(blank=True, null=True)),
                ('isbn', models.TextField(blank=True, null=True)),
                ('lccn', models.TextField(blank=True, null=True)),
                ('path', models.TextField()),
                ('flags', models.IntegerField()),
                ('uuid', models.TextField(blank=True, null=True)),
                ('has_cover', models.BooleanField(blank=True, null=True)),
                ('last_modified', models.TextField()),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksAuthorsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'books_authors_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksCustomColumn1Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'books_custom_column_1_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksLanguagesLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField()),
                ('lang_code', models.IntegerField()),
                ('item_order', models.IntegerField()),
            ],
            options={
                'db_table': 'books_languages_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksPluginData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField()),
                ('name', models.TextField()),
                ('val', models.TextField()),
            ],
            options={
                'db_table': 'books_plugin_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksPublishersLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField()),
                ('publisher', models.IntegerField()),
            ],
            options={
                'db_table': 'books_publishers_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksRatingsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'books_ratings_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksSeriesLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField()),
                ('series', models.IntegerField()),
            ],
            options={
                'db_table': 'books_series_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksTagsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField()),
                ('tag', models.IntegerField()),
            ],
            options={
                'db_table': 'books_tags_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConversionOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.TextField()),
                ('book', models.IntegerField(blank=True, null=True)),
                ('data', models.BinaryField()),
            ],
            options={
                'db_table': 'conversion_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomColumn1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'custom_column_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomColumn2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'custom_column_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('name', models.TextField()),
                ('datatype', models.TextField()),
                ('mark_for_delete', models.BooleanField()),
                ('editable', models.BooleanField()),
                ('display', models.TextField()),
                ('is_multiple', models.BooleanField()),
                ('normalized', models.BooleanField()),
            ],
            options={
                'db_table': 'custom_columns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField()),
                ('format', models.TextField()),
                ('uncompressed_size', models.IntegerField()),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('script', models.TextField()),
            ],
            options={
                'db_table': 'feeds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Identifiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField()),
                ('type', models.TextField()),
                ('val', models.TextField()),
            ],
            options={
                'db_table': 'identifiers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.TextField()),
            ],
            options={
                'db_table': 'languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LastReadPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField()),
                ('format', models.TextField()),
                ('user', models.TextField()),
                ('device', models.TextField()),
                ('cfi', models.TextField()),
                ('epoch', models.FloatField()),
                ('pos_frac', models.FloatField()),
            ],
            options={
                'db_table': 'last_read_positions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LibraryId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField()),
            ],
            options={
                'db_table': 'library_id',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetadataDirtied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField()),
            ],
            options={
                'db_table': 'metadata_dirtied',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('val', models.TextField()),
            ],
            options={
                'db_table': 'preferences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sort', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'publishers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ratings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sort', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'series',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
    ]
